name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Target Device Codename (e.g., lmi, umi)'
        required: true
        default: 'elish'
        type: choice
        options:
          - psyche
          - thyme
          - umi
          - munch
          - lmi
          - cmi
          - cas
          - apollo
          - alioth
          - elish
          - enuma
          - dagu
          - pipa
      ksu:
        description: 'Enable KernelSU (SukiSU & SUSFS)'
        required: true
        type: boolean
        default: true

jobs:
  build:
    name: Build Kernel for ${{ inputs.device }} (${{ ( github.event.inputs.ksu == 'true' && 'KSU' ) || 'NoKSU' }})
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v6
      with:
        fetch-depth: 1 # 需要完整的 commit 历史来生成版本号

    - name: Cleanup Disk Space
      # 内核编译不需要特别大的空间，但为了保险起见，清理一些预装软件
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install Dependencies
      # 对应 README 中的手动构建依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Setup Cache (ccache)
      uses: actions/cache@v5
      with:
        path: ~/.cache/ccache_mikernel
        key: kernel-ccache-${{ inputs.device }}-${{ github.run_id }}
        restore-keys: |
          kernel-ccache-${{ inputs.device }}-
          kernel-ccache-

    - name: Setup Toolchain (ZyC-Clang 22)
      # 对应 Manual Build 第 2 步
      run: |
        mkdir -p $HOME/ZyC-clang
        cd $HOME/ZyC-clang
        wget -q https://github.com/ZyCromerZ/Clang/releases/download/22.0.0git-20250924-release/Clang-22.0.0git-20250924.tar.gz
        tar -zxvf Clang-22.0.0git-20250924.tar.gz

    - name: Build Kernel
      run: |
        chmod +x build.sh
        
        if [ "${{ inputs.ksu }}" == "true" ]; then
          echo "Building with KernelSU..."
          bash build.sh ${{ inputs.device }} ksu
        else
          echo "Building without KernelSU..."
          bash build.sh ${{ inputs.device }}
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Kernel-${{ inputs.device }}-${{ ( github.event.inputs.ksu == 'true' && 'KSU' ) || 'NoKSU' }}-${{ github.run_number }}
        path: ./*.zip
        if-no-files-found: error
